### ISSUE TITLE
其他主题中不能用吗？

### ISSUE THREAD

**Issue by fengwei2002** [Mister-Hope/vuepress-plugin-md-enhance-docs#1]
为什么安装插件了
并且config.js也配置了
plugins: [
    ["md-enhance"],
...

::: right
右
:::

还是没有渲染效果？

**Comment by fengwei2002** [comment]
可能和官方提供的container插件冲突了，已解决

**Comment by Mister-Hope** [comment]
感谢反馈，插件的确可能跟官方的container插件冲突，如果你使用的是默认的官方主题的话，默认会注入 tip warning 和 danger，但插件也会注入同样的块，只不过允许你设置默认语言而不是直接默认为英文。

请问一下你是如何解决的？

**Comment by fengwei2002** [comment]
我用 vuepress-plugin-container 加
index.styl 自定义样式
实现了一样的功能


开始的时候，
我 vuepress 中使用官方插件添加了一个 details 容器 (没写styl文件)
然后使用这个集成插件的时候
其他组件都可以渲染
然后容器不渲染


可能是因为
我自己 index.styl 一开始没添加样式
插件提供了class的绑定
然后再写一个样式就解决了


是否冲突我没测试


打扰了





---原始邮件---
发件人: "Mr.Hope"<notifications@github.com&gt;
发送时间: 2020年5月25日(周一) 下午4:01
收件人: "Mister-Hope/vuepress-plugin-md-enhance-docs"<vuepress-plugin-md-enhance-docs@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"fengwei"<2480417969@qq.com&gt;;
主题: Re: [Mister-Hope/vuepress-plugin-md-enhance-docs] 其他主题中不能用吗？ (#1)




 
感谢反馈，插件的确可能跟官方的container插件冲突，如果你使用的是默认的官方主题的话，默认会注入 tip warning 和 danger，但插件也会注入同样的块，只不过允许你设置默认语言而不是直接默认为英文。
 
请问一下你是如何解决的？
